name: multi_delivery_app
description: A Flutter app for delivery optimization
publish_to: 'none' # remove this line if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  geocoding: ^2.1.0
  provider: ^6.0.5
  path_provider: ^2.1.2
  http: ^1.2.1
  csv: ^5.1.1
  qr_flutter: ^4.1.0
  pdf: ^3.10.4
  share_plus: ^7.2.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true